/* Generated By:JavaCC: Do not edit this line. PetalParserConstants.java */
package cb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PetalParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 4;
  /** RegularExpression Id. */
  int CR = 5;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int TAG = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int MULTI_STRING = 18;
  /** RegularExpression Id. */
  int IN_STRING = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int ANY = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int PLUSMINUS = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(object\"",
    "\")\"",
    "\"(list\"",
    "\"(value\"",
    "\"(\"",
    "\",\"",
    "<INTEGER>",
    "<FLOAT>",
    "<BOOLEAN>",
    "<IDENTIFIER>",
    "<TAG>",
    "<STRING>",
    "<MULTI_STRING>",
    "<IN_STRING>",
    "<LETTER>",
    "<ANY>",
    "<DIGIT>",
    "<PLUSMINUS>",
  };

}
